import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { createApp } from "../src/app/facade.js";
import { ACTION_NAMES } from "../src/app/actions.js";
import { PHASES, OUTPUT_MODES } from "../src/ui/state/phase_state.js";
import { CATALOGUE } from "../src/ui/overlays/composition_overlay_stack.js";
import { MODE_TABLE, LOCK_CHIPS } from "../src/scene/solve_policy.js";
import { t, minCarrierPx, toleranceSetHash } from "../fixtures/tolerances.js";
import landmarks from "../fixtures/P0/landmarks.js";
import { panToPlace, captureToFinal } from "../src/domains/camera/crop.js";
import { gpuSampleUv, shaderUsesKernel } from "../src/domains/recursion/kernel.js";
import { SIZE_BASES } from "../src/domains/content_q/content.js";
import { BUILD } from "../src/app/build_identity.js";
import { PUBLISHED, certifyKernel } from "../fixtures/recursion/kernel.js";
import { SHELL_CSS } from "../src/ui/shell.js";

test("v5 phases and overlay catalogue",()=>{assert.deepEqual(PHASES,["DECLARE","SOLVE","STAGE"]);for(const id of ["GRID","BBOX","CENTROID","MEASURE","PERSPECTIVE","CORRESPONDENCE","VISIBILITY","APPARATUS","RECURSION","DISTORTION"])assert.ok(CATALOGUE.includes(id));});
test("no ROTATE_MIRROR production action",()=>assert.equal(ACTION_NAMES.includes("ROTATE_MIRROR"),false));
test("six solve modes preserve explicit DRIVER / PRESERVE / ALLOWED",()=>{for(const m of ["POSE_FIRST","PHONE_FIRST","MIRROR_RATIO_FIRST","COMPOSITION_FIT","P0_RECONSTRUCT","MANUAL"]){assert.ok(MODE_TABLE[m].driver);assert.ok(Array.isArray(MODE_TABLE[m].preserve));assert.ok(Array.isArray(MODE_TABLE[m].allowed_to_move));}});
test("lock chips name relationships",()=>{const ids=LOCK_CHIPS.map((c)=>c.id);for(const id of ["PHONE_AREA","REFLECTED_BODY_SCALE","MIRROR_OCCUPANCY","SUPPORT","GRIP","P_VALID"])assert.ok(ids.includes(id));});
test("P0 fixture remains explicitly incomplete",()=>{assert.equal(landmarks.y_down,true);assert.equal(landmarks.saved_image_mirrored,"UNDECLARED");assert.equal(landmarks.features.hip_L.status,"missing");assert.equal(landmarks.features.phone.screen_quad.status,"missing");assert.ok(landmarks.features.phone.bbox_centre);});
test("crop pan algebra remains separate from principal point",()=>{const pan=panToPlace([.5,.5],[.727,.1115],1),landed=captureToFinal([.5,.5],{pan,scale:1});assert.ok(Math.abs(landed[0]-.727)<1e-9);assert.ok(Math.abs(landed[1]-.1115)<1e-9);});
test("crop does not change physical R_P",()=>{const app=createApp(),r0=app.getEffective().composition_metrics.R_P_capture;app.dispatch("PAN_OUTER_FRAME",{pan:[.2,-.1]});const r1=app.getEffective().composition_metrics.R_P_capture;assert.ok(Math.abs(r0-r1)<1e-9);});
test("WORLD mirror does not follow the requested phone",()=>{const app=createApp(),m0=app.getEffective().mirror.centre.slice(),p=app.getRequested().phone.transform_request.translation.slice();app.dispatch("SET_MIRROR_DISTANCE_AUTOSOLVE",{on:false});app.dispatch("MOVE_PHONE",{translation:[p[0]+.05,p[1],p[2]]});const m1=app.getEffective().mirror.centre;assert.ok(Math.hypot(m1[0]-m0[0],m1[1]-m0[1],m1[2]-m0[2])<1e-3);});
test("AUTO refuses invalid P and carrier depth can degrade",()=>{const app=createApp();app.dispatch("SET_RECURSION_PARAMETER",{n:8});app.dispatch("SET_PRINT_GALLERY_MODE",{mode:"AUTO"});const rec=app.getEffective().recursion;if(app.getEffective().carrier_p.valid)assert.ok(["EXACT","DEGRADED"].includes(rec.loop_state));else assert.equal(rec.refused,true);assert.ok(minCarrierPx(3)>t("T-LEG"));});
test("solver metadata and x partition",()=>{const e=createApp().getEffective();assert.equal(e.solver.solver_id,"mirror-portrait-nls");assert.ok(e.solver.tolerance_set_hash);assert.ok(e.x_decision.length);assert.ok(e.x_locked.includes("cx"));});
test("target weights retain artist provenance",()=>{const app=createApp();app.dispatch("SET_TARGET_WEIGHT",{id:"phone",weight:2.5,origin:"ARTIST"});const row=app.getRequested().composition.targets.find((x)=>x.id==="phone");assert.equal(row.weight_if_soft,2.5);assert.equal(row.weight_origin,"ARTIST");});
test("all six output modes are reachable and five export products exist",()=>{assert.equal(OUTPUT_MODES.length,6);const app=createApp();const last=app.dispatch("EXPORT_MASK",{width:32,height:32});for(const id of ["EXPORT_FINAL_CAMERA","EXPORT_STAGING_PRESCRIPTION","EXPORT_COMPOSITION_OVERLAY","EXPORT_REFERENCE_RENDER","EXPORT_MASK"])assert.ok(id in last.export.products);assert.equal(last.export.sidecar.build.app,BUILD.app);});
test("Q size bases and recursion kernel remain shared",()=>{assert.deepEqual(SIZE_BASES,["Width%","Height%","Area%","Contain","Cover"]);assert.equal(shaderUsesKernel(),"domains/recursion/kernel.js");const cert=certifyKernel({q:1,n:1,Sval:256,theta_s:0});cert.pole=[.5,.5];cert.beta=[0,0];assert.equal(gpuSampleUv([.6,.4],cert).length,2);});
test("published gamma remains exact",()=>{const c=certifyKernel({q:1,n:1,Sval:256,theta_s:0});assert.ok(Math.abs(c.gamma_abs-PUBLISHED.gamma_abs)<1e-9);assert.ok(Math.abs(c.gamma_arg*180/Math.PI-PUBLISHED.gamma_arg_deg)<1e-6);});
test("snapshots restore requested state",()=>{const app=createApp(),d0=app.getRequested().apparatus.mirror_distance_request_m;app.dispatch("SAVE_SNAPSHOT",{id:"A",kind:"REQUESTED_STATE"});app.dispatch("SET_MIRROR_DISTANCE",{d_M:d0+.2});app.dispatch("LOAD_SNAPSHOT",{id:"A"});assert.ok(Math.abs(app.getRequested().apparatus.mirror_distance_request_m-d0)<1e-9);});
test("LOCK_GRIP remains a real authority",()=>{const app=createApp();app.dispatch("SET_PHONE_AUTHORITY",{authority:"LOCK_GRIP"});assert.equal(app.getRequested().phone.authority,"LOCK_GRIP");assert.equal(app.getRequested().composition.locks.GRIP,true);});
test("shell uses exact v5 tokens, 100dvh, and 44 px controls",()=>{for(const token of ["#FCFBF8","#111111","#C41E63","#2A3FB8","#1E7A4C","#B03A0B","#A96A05"])assert.ok(SHELL_CSS.includes(token));assert.ok(SHELL_CSS.includes("100dvh"));assert.ok(SHELL_CSS.includes("min-height:44px"));assert.ok(SHELL_CSS.includes("grid-template-columns"));});
test("ordinary defaults keep recursion off and user phase DECLARE",()=>{const req=createApp().getRequested();assert.equal(req.recursion.mode,"OFF");assert.equal(req.view.warp_visible,false);assert.equal(req.workspace.phase,"DECLARE");});
test("device matrix still covers phone width",()=>{assert.equal(existsSync(new URL("./ui_device_matrix.json",import.meta.url)),true);const m=JSON.parse(readFileSync(new URL("./ui_device_matrix.json",import.meta.url),"utf8"));assert.ok(m.viewports.some((v)=>v.width===360));});
test("p_log and p_fix remain distinct",()=>{const app=createApp();app.dispatch("SET_PRINT_GALLERY_MODE",{mode:"ADVANCED"});const rec=app.getEffective().recursion;if(rec.certificate){assert.ok("p_log" in rec.certificate);assert.ok("p_fix" in rec.certificate);}});
test("importmap pins three",()=>{const map=JSON.parse(readFileSync(new URL("../importmap.json",import.meta.url),"utf8"));assert.ok(map.imports.three.includes("three@0.170.0"));});
test("tolerance set is versioned",()=>{assert.ok(toleranceSetHash().startsWith("v1:"));assert.equal(t("T-LANDMARK"),.0005);});
